# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce9a96d2d7b8aa6f7206c195e2c3cff060973f9bf9c10a58ef537da0b883bd14e5303b5a09a67069283efca4c4e5b13b22cc41d89970f3f9e5295646ced14012

test:
  secret_key_base: 54179ac612164c4900ad16748ac7597e85d116edb1cfd27202fe978edd2a40344b0893967b56988e830b26e105c36120bbd29fbcc0e403a1b698e3bd47e81350

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
